import type { Metadata } from "next";
import { Nunito, Ubuntu_Sans } from "next/font/google";
import "@/app/styles/_globals.scss";
import "../../../../node_modules/bootstrap/dist/css/bootstrap.min.css";


const nunito = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const ubuntuSans = Ubuntu_Sans({
  variable: "--font-ubuntuSans",
  subsets: ["latin"],
  weight: ["100"], // Укажите нужные веса
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${ubuntuSans.variable}`}>
        <header className="main-header">
          <h1>Диктофон</h1>
        </header>
        {children}
        <footer className="main-footer">
        </footer>
      </body>
    </html>
  );
}
