import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../styles/_globals.scss";
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css"

const nunito = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin","cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <header className="main-header"></header>
        {children}
        <footer className="main-footer"></footer>
      </body>
    </html>
  );
}
